### ISSUE TITLE
Problem Http Cloud Task

### ISSUE THREAD

**Issue by guidogio** [googleapis/java-tasks#639]
Hello,

I've a problem, I need to set header param ( content-type ) when I create an HTTP Cloud Task, but there isn't any possible to do it.

Why?

I see in appengine http request that possibility is present.

**Comment by guidogio** [comment]
I add more information for this ticket.

With appengine http request there is a possibility to add header with method putHeaders ( snippet below )
` AppEngineHttpRequest.newBuilder()
             .setRelativeUri(endpoint)
             .putHeaders("Content-Type", "application/json")
             .setHttpMethod(HttpMethod.POST)
             .setBody(ByteString.copyFrom(payload, StandardCharsets.UTF_8)).build();
`
             
But with the HttpRequest this possibility there isn't ( snippet below )
`
 HttpRequest request = HttpRequest.newBuilder()
            .setBody(ByteString.copyFrom(payload, Charset.defaultCharset()))
            .setHttpMethod(HttpMethod.POST)
            .setUrl(url) //url
            .setOidcToken(oidcTokenBuilder)
            .build();
`

The library is **google-cloud-task** and the version is **2.1.5**

**Comment by averikitsch** [comment]
I have confirmed that using `putHeaders` works for the `HttpRequest`:
```
      Task.Builder taskBuilder =
          Task.newBuilder()
              .setHttpRequest(
                  HttpRequest.newBuilder()
                      .setBody(ByteString.copyFrom(payload, Charset.defaultCharset()))
                      .setUrl(url)
                      .setHttpMethod(HttpMethod.POST)
                      .putHeaders("content-type", "application/json")
                      .build());
```
